In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentances
sent = ["the cat sat on the mat",
         "the dog sat on the log",
         "cats and dogs are great pets",
         "I love my cat",
         "I love my dog",
         "cats and dogs are the best pets",]

In [3]:
sent

['the cat sat on the mat',
 'the dog sat on the log',
 'cats and dogs are great pets',
 'I love my cat',
 'I love my dog',
 'cats and dogs are the best pets']

In [6]:
#Define vocabulary size
vocab_size = 10000

In [7]:
## one hot representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[1697, 7142, 6066, 128, 1697, 4225],
 [1697, 1540, 6066, 128, 1697, 3765],
 [4501, 4656, 6764, 2186, 2305, 1714],
 [32, 1922, 9886, 7142],
 [32, 1922, 9886, 1540],
 [4501, 4656, 6764, 2186, 1697, 7872, 1714]]

In [8]:
## word Embadcing Represnatation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0 1697 7142 6066  128 1697 4225]
 [   0    0 1697 1540 6066  128 1697 3765]
 [   0    0 4501 4656 6764 2186 2305 1714]
 [   0    0    0    0   32 1922 9886 7142]
 [   0    0    0    0   32 1922 9886 1540]
 [   0 4501 4656 6764 2186 1697 7872 1714]]


In [14]:
## Feature Represntaion
dim = 10

In [20]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_shape=(sent_length,)))
model.compile(optimizer="adam", loss="mse")

In [21]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[[-0.01073324, -0.04783459, -0.03560752,  0.02639255,
         -0.01954817, -0.01143584,  0.04726419, -0.04742506,
          0.04597875, -0.02745392],
        [-0.01073324, -0.04783459, -0.03560752,  0.02639255,
         -0.01954817, -0.01143584,  0.04726419, -0.04742506,
          0.04597875, -0.02745392],
        [-0.01964992,  0.0304512 ,  0.04842969, -0.04890409,
          0.00631591,  0.04318238,  0.00033943,  0.0088455 ,
         -0.00588667,  0.00897245],
        [-0.01743443, -0.01784604, -0.01488717, -0.00483542,
         -0.03143872, -0.0495958 ,  0.00481248,  0.04954543,
         -0.04042538,  0.02066708],
        [-0.00018289,  0.0459533 ,  0.02846077, -0.02846644,
         -0.00211246,  0.00034355,  0.00407432, -0.04678982,
          0.04082761,  0.01500226],
        [-0.03050724,  0.02843778, -0.01293999,  0.04133471,
          0.04067734,  0.04959072, -0.02742609, -0.02486088,
         -0.01117657, -0.01386296],
        [-0.01964992,  0.0304512 ,  0.04842969, -0.0